# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Analyze Dart
        # You may pin to the exact commit or the version.
        # uses: zgosalvez/github-actions-analyze-dart@17a5ca792b39421bdaace447ba65be49af8d907d
        uses: zgosalvez/github-actions-analyze-dart@v1.4.0
#         with:
#           # The action fails if any warning was found. This will always fail on errors. Optional. Default: `false`
#           fail-on-warnings: # optional
#           # The working directory. Optional. Default: `./`
#           working-directory: # optional, default is ./
#           # The path to the `analysis_options.yaml` file relative to the `working-directory`. The analyzer will only use the file if it exists. Optional. Default: `analysis_options.yaml`
#           analysis-options-file: # optional, default is analysis_options.yaml

      # This action build and release a Flutter app. [Android, Ios, Web ]
      - name: Flutter Deployment
        # You may pin to the exact commit or the version.
        # uses: jeanluc243/Flutter-Deployment@1fd33eb513293af0c6cde57363d66a6a848ef6e5
        uses: jeanluc243/Flutter-Deployment@0.1
      
      - name: Flutter action
        # You may pin to the exact commit or the version.
        # uses: subosito/flutter-action@26bf50084a0c218b5b715a3641c36eac84fd2136
        uses: subosito/flutter-action@v1.4.0
        #with:
          # The Flutter version to make available on the path
          #flutter-version: # optional
          # The Flutter build release channel
      
